/*
* The darma header
*/

#define EXPORT_SYMTAB

#define DEVICE_NAME "dharma"
#define DEVICE_MAX_NUMBER 256
#define BUFFER_SIZE 1024
#define PACKET_SIZE 64

/* IOCTL related macros */
#define DHARMA_MAJOR 				250
#define DHARMA_SET_PACKET_MODE 		_IO(DHARMA_MAJOR, 0)
#define DHARMA_SET_STREAM_MODE 		_IO(DHARMA_MAJOR, 1)
#define DHARMA_SET_BLOCKING 		_IO(DHARMA_MAJOR, 2)
#define DHARMA_SET_NONBLOCKING 		_IO(DHARMA_MAJOR, 3)
